#!/usr/bin/env node
/**
 * Scans the `dist/` directory and generates a Worker entry point
 * that serves all files as embedded assets with SPA fallback.
 */
import { readdirSync, readFileSync, statSync } from 'fs';
import { join, extname } from 'path';

const DIST_DIR = 'dist';

const MIME_TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff2',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
};

function walk(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      results.push(...walk(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

function main() {
  const files = walk(DIST_DIR);
  const entries = files.map((f) => {
    const relPath = '/' + f.slice(DIST_DIR.length + 1).replace(/\\/g, '/');
    const b64 = readFileSync(f).toString('base64');
    const mime = MIME_TYPES[extname(relPath)] || 'application/octet-stream';
    return `  ${JSON.stringify(relPath)}: {
    body: Uint8Array.from(atob(${JSON.stringify(b64)}), c => c.charCodeAt(0)),
    contentType: ${JSON.stringify(mime)},
  },`;
  });

  return `// Auto-generated by scripts/generate-worker.mjs — do not edit
export default {
  async fetch(request: Request): Promise<Response> {
    const assets: Record<string, { body: Uint8Array; contentType: string }> = {
${entries.join('\n')}
    };

    const url = new URL(request.url);
    let pathname = decodeURIComponent(url.pathname);

    // SPA fallback: no extension → index.html
    if (!pathname.includes('.')) {
      pathname = '/index.html';
    }

    const asset = assets[pathname];
    if (asset) {
      return new Response(asset.body, {
        headers: {
          'Content-Type': asset.contentType,
          'Cache-Control': 'public, max-age=3600',
        },
      });
    }

    return new Response('Not Found', { status: 404 });
  }
};
`;
}

const output = main();
process.stdout.write(output);
